baseurl: /
heme: jekyll-theme-cayman
title: 东莞市巨峰精密设备有限公司
description: 东莞市巨峰精密设备有限公司是一家私营企业成立于2015年。主要业务范围：精密机械设备，标准自动化设备，非标自动设备（自动化生产线，自动装配，自动印刷，自动测试检测，自动包装，注塑机边自动化设备），高精密切水口夹具，检测夹具，机械设备的技术开发及销售；喷涂线，电镀线，氧化线，隧道炉，烤箱，流水线，废气废水处理设备；国内贸易。
